include:
   - local: 'scanner.yml'

scan:
  stage: build
  rules:
    # execute on pushes to the main branch
    - if: ($CI_PIPELINE_SOURCE == "push") && ($CI_COMMIT_BRANCH == "main")
    # execute on pull request synchronization
    - if: ($CI_PIPELINE_SOURCE == "external_pull_request_event") || ($CI_PIPELINE_SOURCE == "merge_request_event")
  extends:
    - .boost_scan
  script:
    - env |grep ^CI_
  variables:
    BOOST_API_ENABLED: "false"
    BOOST_CLI_VERSION: "1.0.0.rc129"
    BOOST_SCANNER_REGISTRY_MODULE: "boostsecurityio/native-scanner"
    CI_MERGE_REQUEST_IID: $CI_EXTERNAL_PULL_REQUEST_IID
    CI_MERGE_REQUEST_DIFF_BASE_SHA: $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_SHA
