include:
   - local: 'scanner.yml'

scan:
  stage: build
  extends:
    - .boost_scan
  variables:
    BOOST_API_TOKEN: $BOOST_API_TOKEN
    BOOST_SCANNER_REGISTRY_MODULE: "boostsecurityio/native-scanner"
