include:
   - local: 'scanner.yml'

variables:
  CI_DEBUG_SERVICES: "true"

scan:
  stage: build
  extends:
    - .boost_scan
  variables:
    BOOST_SCANNER_REGISTRY_MODULE: "boostsecurityio/native-scanner"
