include:
   - local: 'scanner.yml'

scan:
  stage: build
  extends:
    - .boost_scan
  script:
    - env |grep ^CI_
  variables:
    BOOST_API_ENABLED: "false"
    BOOST_CLI_VERSION: "1.0.0.rc129"
    BOOST_SCANNER_REGISTRY_MODULE: "boostsecurityio/native-scanner"
